import Head from 'next/head'
import { Menu } from '../components/Navbar'

export default function Home() {
	return (
		<div>
			<Head>
				<title>Cartório São Gonçalo dos Campos</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Menu />
		</div>
	)
}
